version: "3"
services: 
  app: 
    build: 
      context: .
      dockerfile: Dockerfile
    
    entrypoint: 
      - ./wait.sh
    ports: 
      - "8000:8000"
  db: 
    environment: 
      MYSQL_ROOT_PASSWORD: root
    image: "mysql:8.0.21"
    ports: 
      - "30000:3306"
    volumes: 
      - "./db:/docker-entrypoint-initdb.d/:ro"

